baskets/urls.py
from django.contrib import admin
from django.urls import path


from baskets.views import basket_add, basket_remove, basket_edit


app_name = 'baskets'

urlpatterns = [
    path('basket_add/<int:id>', basket_add, name='basket_add'),
    path('delete/<int:id>', basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from products.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar

    urlpatterns += [path('^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path
from django.contrib import admin

from .views import OrderList, OrderCreate, OrderRead, OrderDelete, OrderUpdate, order_forming_complete, payment_result, get_product_price

app_name = 'ordersapp'

urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('read/<int:pk>/', OrderRead.as_view(), name='read'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('forming-complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('payment/result/', payment_result, name='payment_result'),
    path('product/<int:pk>/price/', get_product_price, name='product_price'),
]

products/urls.py
from django.contrib import admin
from django.urls import path


from products.views import ProductDetailView, ProductsListView
# from products.views import products,

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='index'),
    path('category/<int:pk>', ProductsListView.as_view(), name='category'),
    path('page/<int:page>', ProductsListView.as_view(), name='page'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product'),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import UserLoginView, UserCreateView, UserUpdateView, logout, verify
# from users.views import register, profile, login


app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('logout/', logout, name='logout'),
    path('profile/<int:pk>', UserUpdateView.as_view(), name='profile'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

products/models.py
from django.db import models


# Create your models here.

class ProductsCategory(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True, db_index=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=64)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductsCategory, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True, db_index=True)

    def __str__(self):
        return f'{self.name} | {self.category}'

products/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.cache import cache_page
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.core.cache import cache


import os
from products.models import ProductsCategory, Product


MODULE_DIR = os.path.dirname(__file__)

# Create your views here.


def get_links_category():
    if settings.LOW_CACHE:
        key = 'links_category'
        links_category = cache.get(key)

        if links_category is None:
            links_category = ProductsCategory.objects.filter(is_active=True)
            cache.set(key, links_category)
        return links_category
    else:
        return ProductsCategory.objects.filter(is_active=True)


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product{pk}'
        product = cache.get(key)

        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_links_product():
    if settings.LOW_CACHE:
        key = 'links_product'
        links_product = cache.get(key)

        if links_product is None:
            links_product = Product.objects.filter(is_active=True).select_related()
            cache.set(key, links_product)
        return links_product
    else:
        return Product.objects.filter(is_active=True).select_related()


def index(request):
    context = {'title': "GeekShop"}
    return render(request, 'index.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['title'] = 'Подробно о товаре'
        context['product'] = get_product(self.kwargs.get('pk'))
        return context


# def product(request, id):
#     product = Product.objects.filter(id=id)
#     context = {
#         'title': 'Подробно о товаре',
#         'product': product
#     }
#     return render(request, 'product.html', context)


class ProductsListView(ListView):
    model = Product
    template_name = 'products.html'
    paginate_by = 3

    # @cache_page(3600)
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['title'] = 'Каталог'
        context['category'] = get_links_category()
        # context['category'] = ProductsCategory.objects.all()
        # context['products'] = self.products_paginator(self)
        return context

    # def products_paginator(self, pk=None, page=1):
    #     products = Product.objects.filter(category_id=pk) if pk is not None else Product.objects.all()
    #     paginator = Paginator(products, per_page=3)
    #     try:
    #         products_paginator = paginator.page(page)
    #     except PageNotAnInteger:
    #         products_paginator = paginator.page(1)
    #     except EmptyPage:
    #         products_paginator = paginator.page(paginator.num_pages)
    #     return products_paginator

# def products(request, id=None, page=1):
#     products = Product.objects.filter(category_id=id) if id is not None else Product.objects.all()
#     paginator = Paginator(products, per_page=3)
#     try:
#         products_paginator = paginator.page(page)
#     except PageNotAnInteger:
#         products_paginator = paginator.page(1)
#     except EmptyPage:
#         products_paginator = paginator.page(paginator.num_pages)
#     context = {"title": "Каталог"}
#     context['category'] = ProductsCategory.objects.all()
#     context['products'] = products_paginator
#     return render(request, 'products.html', context)

products/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block title %}

        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %}

    {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop  {% now "d.m.Y" %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% else %}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}#}
{#                            <i class="fas fa-user-circle"></i>#}
{#                        </a>#}
{#                    </li>#}
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
                                {{ user.username|default:'Пользователь' }}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'users:profile' user.id %}">
                                        Профиль
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'orders:list' %}">
                                        Заказы
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>

                    {% if user.is_staff or user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admins:index' %}">
                                <i class="fas fa-users-cog"></i>
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}

{% endblock %}

{% block footer %}
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2021</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/baskets.js' %}"></script>
<script src="{% static 'js/orders_scripts.js' %}"></script>

</body>

</html>

products/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ 'geekshop'|title }}
{% endblock %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}

{% endblock %}

products/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ 'geekshop - каталог'|title }}
{% endblock %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="row">
                    <div class="col-lg-7 col-md-6 mb-4">
                        <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top" src="{{ product.image.url }}" alt="">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#">{{ product.name }}</a>
                                </h4>
                                <p class="card-text">{{ product.description }}</p>
                                <h5>Категория товара: {{ product.category }}</h5>
                                <h5>Цена: {{ product.price }} руб.</h5>
                                <h5>Остаток на складе: {{ product.quantity }} шт.</h5>
                            </div>
                            <div class="card-footer text-center">
                                <a href="{% url 'baskets:basket_add' product.id %}" type="button"
                                   class="btn btn-outline-success">Отправить в корзину</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

products/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ 'geekshop - каталог'|title }}
{% endblock %}

{% block css %}
    <link href="{% static '/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'products:index' %}" class="list-group-item">Все категории</a>
                    {% for category in category %}
                        <a href="{% url 'products:category' category.pk %}" class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">

                    {% for product in page_obj %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="{{ product.image.url }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{% url 'products:product' product.pk %}">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }} руб.</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'baskets:basket_add' product.id %}" type="button" class="btn btn-outline-success">Отправить в корзину</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>

                <div class="pagination justify-content-center">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container -->
{% endblock %}